[package]
name = "glsl_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
revier_graphic = {path="../revier_graphic",version = "0.1.0"}

