[package]
name = "lumina_bundle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = {version="0.37.3",features = ["linked", "debug"]}
