[package]
name = "lumina_path"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lumina_files = {path="../lumina_files",version = "0.1.0"}
